### ISSUE TITLE
Patch Request

### ISSUE THREAD

**Issue by RF-PT** [pharaox/artifact_trade#2]
Hey @pharaox.

I wanted to ask if is possible to make your amazing mod compatible with this one: https://steamcommunity.com/sharedfiles/filedetails/?id=2990228836

I have requested trough PM to the owner, he read the message and didnt reply, other people have requested patch as well, and he seems to not have any interest in changing/adding compatibility to other mods, he even says in the page of the owner of his mods that he is making changes to personal use only.

I would love to be able to use your awesome mod with is changes to inventory, is possible to have a compatibility patch or something?

Awaiting for your reply, love your work, thank you from the bottom of my heart for your work for this community, best regards from Portugal.

**Comment by pharaox** [comment]
Hi @RF-PT , thanks for the suggestion. I haven't tried it, but likely the two mods are already compatible except for changes to the Inventory window, so if you load More Artifact Slots after this one "Buy Artifacts" and "Sell Artifacts" buttons will be missing, but the rest will work. Same story as with the Artifact Manager mod. 

Maintaining multiple compatibility patches for mods that change the Inventory window in totally different and mutually incompatible ways is not something I am very fond of doing. However, I do understand the issue, so I am thinking about alternatives that would not require patches. What I want to do is make "Buy Artifacts" and "Sell Artifacts" available in one different alternative location besides the Inventory window. Let me think about it some more.

**Comment by RF-PT** [comment]
@pharaox for sure, take your time, and i understand what you mean.

Hoping that you can make them work together, in some way, once again thank you from the bottom of my heart for your time/work.

**Comment by pharaox** [comment]
@RF-PT I know this took a long time on my side, but finally in the latest version of STA I added the "Buy Artifacts" and "Sell Artifacts" button to the "Artifact Finder" window, as it's the only UI window that is part of STA and so far not touched by other mods. This should make STA compatible with all mods that modify the Inventory window, including "More Artifact Slots".
